export const SET_MESSAGES = 'SET_MESSAGES'
export const SET_USERS = 'SET_USERS'
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER'
export const SET_CHATS = 'SET_CHATS'
export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT'
